### PR TITLE
Add support for s390[x].

### PR DESCRIPTION
**Pull request by xnox**
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

### CODE REVIEW

**Comment by xnox** [comment]
I have tested this on s390x, but not on s390 as i don't have such a system/config/compiler. But it should be correct, w.r.t. defines.

**Comment by behlendorf** [comment]
@xnox this looks reasonable to me, although I wish I had a way to verify it.  When you open the ZFS counterpart for this patch which modifies `lib/libspl/include/sys/isa_defs.h` similarly please add the following line to reference this PR.  That will cause the buildbot to automatically test both of these patches.

```
Requires-spl: refs/pull/537/head
```

**Comment by ryao** [comment]
@behlendorf Verifying it can be done by installing a Linux distribution that supports the z/architecture inside the Hercules emulator and then ZoL inside of that.

**Comment by xnox** [comment]
actually i believe VTOC should not be defined here, but is appropriate for the zfs repo.

**Comment by ryao** [comment]
@xnox We will need either _SUNOS_VTOC_16 or _SUNOS_VTOC_8 defined. Otherwise, `lib/libspl/include/sys/dklabel.h` will trigger a build failure from `#error No VTOC format defined.`. Everyone else defined `_SUNOS_VTOC_16`, so we probably could get away with defining that too.

**Comment by xnox** [comment]
@ryao yes, which is what i did in the zfs copy of libspl. There are two copies of this code as far as i can see. And in zfs repo more arches define  _SUNOS_VTOC_16, unlike in this repo.

**Comment by ryao** [comment]
@xnox You are correct. I mistook this for the issue in the zfs repository.

**Comment by behlendorf** [comment]
Merged as:

224817e Add support for s390[x].

**Pull request closed without merging**
