### PR TITLE
Additional dkio support for TRIM/Discard

### PR DESCRIPTION
**Pull request by dweeezil**
Replace DKIOCTRIM with DKIOCFREE and add additional support required
for Nextenta's TRIM support.

### CODE REVIEW

**Comment by dweeezil** [comment]
This is a prerequisite for my port of Nexenta's TRIM support.

**Comment by behlendorf** [comment]
@dweeezil I'd be very tempted to use this as an opportunity to pull the dkio code out of the spl and in to the zfs tree.  That way we can continue to merge the two trees.

**Comment by behlendorf** [comment]
@dweeezil sorry about the delay.  I'm happy to merge this to make testing easier if it's finalized.

**Comment by dweeezil** [comment]
@behlendorf I can't see any need to change this particular patch any further and consider it to be ready to merge.

**Comment by behlendorf** [comment]
Merged:

e5f9a9a Additional dkio support for TRIM/Discard

**Pull request closed without merging**
