### PR TITLE
spl 0.6.5.10-rc

### PR DESCRIPTION
**Pull request by tonyhutter**
SPL 0.6.5 updates

### CODE REVIEW

**Comment by behlendorf** [comment]
@tonyhutter you're going to want to add the following build fixes to this branch.

8f87971 Linux 4.12 compat: PF_FSTRANS was removed
481762f glibc 2.25 compat: remove assert(X=Y)
bf8abea Linux 4.11 compat: remove stub for __put_task_struct
9a054d5 Linux 4.11 compat: add linux/sched/signal.h
94b1ab2 Linux 4.11 compat: vfs_getattr() takes 4 args
e0aacd9 Fix powerpc build
8d5feec Linux 4.11 compat: set_task_state() removed

**Comment by tonyhutter** [comment]
@behlendorf thanks, will do.

**Comment by tonyhutter** [comment]
@behlendorf I cherry picked your commits and added d5f788c to resolve a dependency with b129b71.

**Comment by Lalufu** [comment]
Where are we with this? Fedora has started rolling out 4.11 to FC25.

**Comment by tonyhutter** [comment]
@Lalufu I talked with @behlendorf offline about it yesterday.  Were really close to getting a 0.6.5.10 release.  Just three more patches to merge.  Probably have something out this week or next week.

**Comment by tonyhutter** [comment]
Released
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.6.5.10

**Pull request closed without merging**
