### PR TITLE
Add rw_tryupgrade()

### PR DESCRIPTION
**Pull request by behlendorf**
This implementation of rw_tryupgrade() behaves slightly differently
from its counterparts on other platforms.  It drops the RW_READER lock
and then acquires the RW_WRITER lock leaving a small window where no
lock is held.  On other platforms the lock is never released during
the upgrade process.  This is necessary under Linux because the kernel
does not provide an upgrade function.

There are currently no callers in the ZFS code where this change in
behavior is a problem.  In fact, in most cases the code is already
written such that if the upgrade fails the RW_READER lock is dropped
and the caller blocks waiting to acquire the lock as RW_WRITER.

Signed-off-by: Brian Behlendorf <behlendorf1@llnl.gov>
Issue zfsonlinux/zfs#4388
Issue #534

### CODE REVIEW

**Comment by prometheanfire** [comment]
What additional testing is needed for this?

**Comment by dweeezil** [comment]
LGTM, pretty much as expected.  The pr does seem to have survived the 'bots.

**Comment by behlendorf** [comment]
@prometheanfire if you could independently verify it resolves the prefetch issue that would be great.

@dweeezil thanks for the quick review.

**Comment by prometheanfire** [comment]
tested via scrub on a 10G mirror (over iscsi attached volumes using nova/cinder)

without: 276M/s (completed in less than a minute)
with patch: 279M/s (less than a minute)

guess I'll try with fio?

**Comment by dweeezil** [comment]
@prometheanfire You want to look at ```/proc/spl/kstat/zfs/zfetchstats```.

**Comment by prometheanfire** [comment]
with

    name                            type data
    hits                            4    238
    misses                          4    64112
    max_streams                     4    63163

without

    name                            type data
    hits                            4    0
    misses                          4    50996
    max_streams                     4    0

**Comment by behlendorf** [comment]
Looks good.  OK, then I'll get this merged and add @dweeezil's signed-off-by.  @prometheanfire thanks for the confirmation.

**Comment by behlendorf** [comment]
Merged as:

a6ae97c Add rw_tryupgrade()

**Pull request closed without merging**
